# Generated by Django 3.0.3 on 2020-02-25 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('active_start_date', models.DateField(default=datetime.date.today)),
                ('active_end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active_start_date', models.DateField(default=datetime.date.today)),
                ('active_end_date', models.DateField(blank=True)),
                ('client_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('git_url', models.CharField(max_length=250)),
                ('testing_url', models.CharField(blank=True, max_length=250)),
                ('production_url', models.CharField(blank=True, max_length=250)),
                ('libraries', models.ManyToManyField(to='api.LibraryEntries')),
            ],
        ),
    ]
