# Generated by Django 3.0.3 on 2020-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200225_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='production_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
