# Generated by Django 3.0.3 on 2020-02-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200225_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='api.LibraryEntries'),
        ),
    ]
